export enum AppRoutes {
  HOME = "/",
  LOGIN_PAGE = "/login-page",
  SIGN_UP_PAGE = "/sign-up-page",
  MOVIELIST_PAGE = "/movie-list-page",
  MOVIEDETAIL_PAGE = "/movies/:movieId",
  THEATERLIST_PAGE = "/theater-list-page",
  SCHEDULE_PAGE = "/schedule-page",
  RESERVATION_PAGE = "/reservation-page",
  SEAT_SELECTION_PAGE = "/seat-selection-page",
  PAYMENT_PAGE = "/payment-page",
  TICKET_PAGE = "/ticket-page",
  MY_PAGE = "/my-page",
  ADMIN_PAGE = "/admin-page",
}
